// Mocks generated by Mockito 5.4.6 from annotations
// in auth_sample/test/features/auth/data/datasource/remote/auth_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:auth_sample/core/network/dio_factory.dart' as _i4;
import 'package:auth_sample/core/services/encrypted_payload.dart' as _i3;
import 'package:auth_sample/core/services/encryption_service.dart' as _i6;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptedPayload_1 extends _i1.SmartFake
    implements _i3.EncryptedPayload {
  _FakeEncryptedPayload_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioFactory extends _i1.Mock implements _i4.DioFactory {
  MockDioFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {#data: data, #queryParameters: queryParameters},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [AesEncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAesEncryptionService extends _i1.Mock
    implements _i6.AesEncryptionService {
  MockAesEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateKey, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateKey, []),
            ),
          )
          as String);

  @override
  _i3.EncryptedPayload encrypt({
    required String? plainText,
    required String? base64Key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [], {
              #plainText: plainText,
              #base64Key: base64Key,
            }),
            returnValue: _FakeEncryptedPayload_1(
              this,
              Invocation.method(#encrypt, [], {
                #plainText: plainText,
                #base64Key: base64Key,
              }),
            ),
          )
          as _i3.EncryptedPayload);

  @override
  String decrypt({
    required String? base64Encrypted,
    required String? base64Iv,
    required String? base64Key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [], {
              #base64Encrypted: base64Encrypted,
              #base64Iv: base64Iv,
              #base64Key: base64Key,
            }),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#decrypt, [], {
                #base64Encrypted: base64Encrypted,
                #base64Iv: base64Iv,
                #base64Key: base64Key,
              }),
            ),
          )
          as String);
}
