// Mocks generated by Mockito 5.4.6 from annotations
// in auth_sample/test/features/auth/data/repository/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:auth_sample/core/services/encrypted_payload.dart' as _i5;
import 'package:auth_sample/core/services/encryption_service.dart' as _i9;
import 'package:auth_sample/core/services/storage_service.dart' as _i8;
import 'package:auth_sample/features/auth/data/datasource/remote/auth_remote_data_source.dart'
    as _i6;
import 'package:auth_sample/features/auth/data/models/auth_session_model.dart'
    as _i2;
import 'package:auth_sample/features/auth/data/models/user_model.dart' as _i3;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthSessionModel_0 extends _i1.SmartFake
    implements _i2.AuthSessionModel {
  _FakeAuthSessionModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_2 extends _i1.SmartFake
    implements _i4.FlutterSecureStorage {
  _FakeFlutterSecureStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptedPayload_3 extends _i1.SmartFake
    implements _i5.EncryptedPayload {
  _FakeEncryptedPayload_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i6.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AuthSessionModel> login({
    required String? email,
    required String? password,
    required String? userKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #email: email,
              #password: password,
              #userKey: userKey,
            }),
            returnValue: _i7.Future<_i2.AuthSessionModel>.value(
              _FakeAuthSessionModel_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                  #userKey: userKey,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.AuthSessionModel>);

  @override
  _i7.Future<_i3.UserModel> register({
    required String? name,
    required String? email,
    required String? password,
    required String? newUserKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
              #newUserKey: newUserKey,
            }),
            returnValue: _i7.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                  #newUserKey: newUserKey,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.UserModel>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i8.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FlutterSecureStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFlutterSecureStorage_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.FlutterSecureStorage);

  @override
  _i7.Future<bool> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, String>> readAll() =>
      (super.noSuchMethod(
            Invocation.method(#readAll, []),
            returnValue: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<bool> saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [AesEncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAesEncryptionService extends _i1.Mock
    implements _i9.AesEncryptionService {
  MockAesEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateKey, []),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#generateKey, []),
            ),
          )
          as String);

  @override
  _i5.EncryptedPayload encrypt({
    required String? plainText,
    required String? base64Key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [], {
              #plainText: plainText,
              #base64Key: base64Key,
            }),
            returnValue: _FakeEncryptedPayload_3(
              this,
              Invocation.method(#encrypt, [], {
                #plainText: plainText,
                #base64Key: base64Key,
              }),
            ),
          )
          as _i5.EncryptedPayload);

  @override
  String decrypt({
    required String? base64Encrypted,
    required String? base64Iv,
    required String? base64Key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [], {
              #base64Encrypted: base64Encrypted,
              #base64Iv: base64Iv,
              #base64Key: base64Key,
            }),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#decrypt, [], {
                #base64Encrypted: base64Encrypted,
                #base64Iv: base64Iv,
                #base64Key: base64Key,
              }),
            ),
          )
          as String);
}
